---

- name: Install apt packages playbook
  hosts: all
  roles:
    - role: ../asbl-apt_packages_install
      become: true
      become_user: "{{ root_username | default('root') }}"
      tags: [apt_packages_install]
