---
# Description : Install package from source
# file : _install_from_source.yml
# Source : https://docs.ansible.com/ansible/latest/collections/ansible/builtin/package_module.html

## update sources (apt update) if the last one is more than 3600 seconds ago
- name: Update apt sources
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

## install desired package with apt
- name: Install the desired package from apt_source_package_list
  ansible.builtin.apt:
    pkg: "{{ apt_source_package_list }}"
    state: present
  when: apt_source_package_list is defined and apt_source_package_list is iterable
  register:  apt_source_package_result
  until: apt_source_package_result is succeeded
  retries: 3
  delay: 10

## uninstall desired package with apt
- name: Remove the desired package from apt_source_remove_package_list
  ansible.builtin.apt:
    pkg: "{{ apt_source_remove_package_list }}"
    state: absent
    autoremove: true
  when: apt_source_remove_package_list is iterable and apt_source_remove_package_list is defined
  register:  apt_source_remove_result
  until: apt_source_remove_result is succeeded
  retries: 3
  delay: 10