---
# Description : Install package
# file : main.yml
# Source : https://docs.ansible.com/ansible/latest/collections/ansible/builtin/package_module.html

## Gather the installed package list on the server
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto
  when: ansible_facts.packages is not defined

- import_tasks: _install_from_source.yml
  tags: [_install_from_source]

- import_tasks: _install_from_url.yml
  tags: [_install_from_url]
  when: apt_url_package_list is defined and apt_url_package_list is iterable